apiVersion: v1
kind: ConfigMap
metadata:
  name: htcondor-{{ .Values.Instance }}-configuration
  labels:
    app: htcondor
    instance: {{ .Values.Instance }}
data:
  condor_config.local: |-
{{ .Values.CondorConfigFile | indent 4 }}
