apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "condor.fullname" . }}
  labels:
    app: {{ template "condor.fullname" . }}
    chart: {{ template "condor.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: {{ .Values.CondorConfig.Instances }}
  selector:
    matchLabels:
      app: {{ template "condor.fullname" . }}
      chart: {{ template "condor.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "condor.fullname" . }}
        chart: {{ template "condor.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: executedir
        {{ if .Values.CondorConfig.ExecuteDir }}
        hostPath:
          path: {{ .Values.CondorConfig.ExecuteDir }} 
          type: Directory
        {{ else }}
        emptyDir: {}
        {{ end }}  
      {{ if .Values.CondorConfig.Cvmfs }}
      - name: config-osg
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-config-osg-{{ .Values.Instance }}
      - name: oasis
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-oasis-{{ .Values.Instance }}
      - name: spt
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-spt-{{ .Values.Instance }}
      - name: connect
        persistentVolumeClaim:
          claimName: csi-cvmfs-pvc-connect-{{ .Values.Instance }}
      {{ end }}
      - name: condor-passwordfile-volume
        secret:
          secretName: {{ .Values.CondorConfig.PasswordFileSecret }}
          items: 
          - key: condor_password
            path: condor_password
            mode: 256
      - name: htcondor-{{ .Values.Instance }}-configuration
        configMap:
          name: htcondor-{{ .Values.Instance}}-configuration
      containers:
      - name: htcondor-worker
        image: slateci/container-condor:latest
        volumeMounts:
        - name: executedir
          mountPath: /var/lib/condor/execute
        - name: condor-passwordfile-volume
          mountPath: /etc/condor/condor_password
          subPath: condor_password
        - name: htcondor-{{ .Values.Instance}}-configuration
          mountPath: /etc/condor/condor_config.local
          subPath: condor_config.local
        {{ if .Values.CondorConfig.Cvmfs }}
        - name: config-osg
          mountPath: /cvmfs/config-osg.opensciencegrid.org
        - name: oasis
          mountPath: /cvmfs/oasis.opensciencegrid.org
        - name: spt
          mountPath: /cvmfs/spt.opensciencegrid.org
        - name: connect
          mountPath: /cvmfs/connect.opensciencegrid.org
        {{ end }}
        env:
        - name: _CONDOR_COLLECTOR_HOST
          value: {{ .Values.CondorConfig.CollectorHost | quote }}
        {{ if .Values.CondorConfig.MemoryLimit }}
        - name: _CONDOR_MEMORY
          value: {{ .Values.CondorConfig.MemoryLimit | quote }}
        {{ end}}
        {{ if .Values.CondorConfig.NumCPUs }}
        - name: _CONDOR_NUM_CPUS
          value: {{ .Values.CondorConfig.NumberCPUs | quote }}
        {{ end}}
        - name: _CONDOR_NETWORK_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            {{ if .Values.CondorConfig.MemoryLimit }}
            memory: "{{ .Values.CondorConfig.MemoryLimit }}Mi"
            {{ end}}
            {{ if .Values.CondorConfig.NumCPUs }}
            cpu:    "{{ .Values.CondorConfig.NumCPUs }}000m"
            {{ end}}
          {{ if .Values.CondorConfig.UseGPU }}
          limits:
            nvidia.com/gpu: {{ .Values.CondorConfig.NumberGPUs }}
          {{ end }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/condor_off","-peaceful"]
