apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-pvc-spt-{{ .Values.Instance }}
  labels:
    app: {{ template "htcondor.name" . }}
    chart: {{ template "htcondor.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-spt