apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-pvc-spt-{{ .Values.Instance }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-spt