apiVersion: v1
kind: Service
metadata:
  name:  {{ include "login-node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ include "login-node.name" . }}
    instance: {{ .Values.Instance }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
