apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflow-server
  labels:
    app: nextflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextflow-server
  template:
    metadata:
      labels:
        app: nextflow-server
    spec:
      containers:
      - name: nextflow-server
        image: bentsherman/nextflow-gke
        env:
        - name: NEXTFLOW_K8S
          value: "true"
        command:
        - /bin/bash
        - -c
        - cd /opt/nextflow-gke; python3 server.py
        resources:
          requests:
            cpu: 1
            memory: 4Gi
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        ports:
        - containerPort: 8080
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: deepgtex-prp
