apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nextflow-api.fullname" . }}
  labels:
    app: {{ template "nextflow-api.name" . }}
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nextflow-server.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "nextflow-api.name" . }}
          servicePort: 8080
