kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nextflow-api.name"}}-deepgtex-prp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-provisioner
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.Size }}