apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stashcache.fullname" . }}
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "stashcache.name" . }}
      chart: {{ template "stashcache.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "stashcache.name" . }}
        chart: {{ template "stashcache.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: stashcache-config
        configMap:
          name: stashcache-config-{{ .Values.Instance }}
          items:
          - key: xrootd-stashcache-cache-server.cfg
            path: xrootd-stashcache-cache-server.cfg
          - key: Authfile-noauth
            path: Authfile-noauth
          - key: Authfile-auth
            path: Authfile-auth
          - key: stashcache-robots.txt
            path: stashcache-robots.txt
      - name: stashcache-data
        {{ if .Values.StashCache.CacheDirectory }}
        hostPath:
          path: {{ .Values.StashCache.CacheDirectory }}
        {{ else }}
        emptyDir: {}
        {{ end }}
      - name: host-certificate
        secret:
          secretName: {{ .Values.hostCertSecret }}
          items:
          - key: hostcert
            path: hostcert.pem
      - name: host-key
        secret:
          secretName: {{ .Values.hostKeySecret }} 
          items:
          - key: hostkey
            path: hostkey.pem
      containers:
      - name: stashcache
        image: opensciencegrid/stash-cache:20190416-2322
        imagePullPolicy: Always
        command: ['su', '-p', 'xrootd', '-s', '/bin/sh', '-c', '/usr/bin/xrootd -c /etc/xrootd/xrootd-stashcache-cache-server.cfg -k fifo -s /var/run/xrootd/xrootd-stashcache-cache-server.pid -n stashcache-cache-server']
        env:
        - name: STASHCACHE_LOCAL_CACHE_DIR
          value: {{ .Values.StashCache.CacheDirectory | quote }}
        - name: STASHCACHE_SPACE_HIGH_WM
          value: {{ .Values.StashCache.HighWaterMark | quote }}
        - name: STASHCACHE_SPACE_LOW_WM
          value: {{ .Values.StashCache.LowWaterMark | quote }}
        - name: STASHCACHE_RAMSIZE
          value: {{ .Values.StashCache.RamSize | quote }}
        - name: STASHCACHE_BLOCKSIZE
          value: {{ .Values.StashCache.BlockSize | quote }}
        - name: STASHCACHE_PREFETCH
          value: {{ .Values.StashCache.Prefetch | quote }}
        - name: STASHCACHE_SITE_NAME
          value: {{ .Values.Site.Name | quote }}
        - name: STASHCACHE_MONITORING_ENDPOINT
          value: "uct2-collectd.mwt2.org"
        volumeMounts:
        - mountPath: "/etc/xrootd/"
          name: stashcache-config
          readOnly: false
        - mountPath: "/stash"
          name: stashcache-data
          readOnly: false
        - mountPath: /etc/grid-security/hostcert.pem
          name: host-certificate
          readOnly: false
          subPath: hostcert.pem 
        - mountPath: /etc/grid-security/hostkey.pem
          name: host-key
          readOnly: false
          subPath: hostkey.pem
        livenessProbe:
          tcpSocket:
            port: {{ .Values.Service.Port }}
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: {{ .Values.Service.Port }}
