apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stashcache.fullname" . }}
  labels:
    app: {{ template "stashcache.name" . }}
    chart: {{ template "stashcache.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "stashcache.name" . }}
      chart: {{ template "stashcache.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "stashcache.name" . }}
        chart: {{ template "stashcache.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: stashcache-config
        configMap:
          name: stashcache-config-{{ .Values.Instance }}
          items:
          - key: Authfile-noauth
            path: Authfile-noauth
          - key: Authfile-auth
            path: Authfile-auth
          - key: stashcache-robots.txt
            path: stashcache-robots.txt
      - name: stashcache-data
        {{ if .Values.StashCache.CacheDirectory }}
        hostPath:
          path: {{ .Values.StashCache.CacheDirectory }}
        {{ else }}
        emptyDir: {}
        {{ end }}  
      {{ if .Values.hostCertSecret}}
      - name: host-certificate
        secret:
          secretName: {{ .Values.hostCertSecret }}
          items:
          - key: hostcert.pem
            path: hostcert.pem
          - key: hostkey.pem
            path: hostkey.pem
      {{ end }}
      containers:
      - name: stashcache
        image: opensciencegrid/stash-cache:20190419-1555
        imagePullPolicy: Always
        env:
        - name: XC_ROOTDIR
          value: "/stash"
        # These Settings are not yet supported in the OSG image
        #- name: STASHCACHE_SPACE_HIGH_WM
        #  value: {{ .Values.StashCache.HighWaterMark | quote }}
        #- name: STASHCACHE_SPACE_LOW_WM
        #  value: {{ .Values.StashCache.LowWaterMark | quote }}
        #- name: STASHCACHE_RAMSIZE
        #  value: {{ .Values.StashCache.RamSize | quote }}
        #- name: STASHCACHE_BLOCKSIZE
        #  value: {{ .Values.StashCache.BlockSize | quote }}
        #- name: STASHCACHE_PREFETCH
        #  value: {{ .Values.StashCache.Prefetch | quote }}
        - name: XC_RESOURCENAME
          value: {{ .Values.Site.Name | quote }}
        #- name: STASHCACHE_MONITORING_ENDPOINT
        #  value: "uct2-collectd.mwt2.org"
        volumeMounts:
        - name: stashcache-config
          mountPath: "/etc/xrootd/Authfile-noauth"
          subPath: Authfile-noauth
        - name: stashcache-config
          mountPath: "/etc/xrootd/Authfile-auth"
          subPath: Authfile-auth
        - name: stashcache-config
          mountPath: "/etc/xrootd/stashcache-robots.txt"
          subPath: stashcache-robots.txt
        - mountPath: "/stash"
          name: stashcache-data
          readOnly: false
        {{ if .Values.hostCertSecret }}
        - mountPath: /etc/grid-security/hostcert.pem
          name: host-certificate
          readOnly: true
          subPath: hostcert.pem 
        - mountPath: /etc/grid-security/hostkey.pem
          name: host-certificate
          readOnly: true
          subPath: hostkey.pem
        {{ end }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.Service.Port }}
          initialDelaySeconds: 180
          periodSeconds: 60
        ports:
        - containerPort: {{ .Values.Service.Port }}
