apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: {{ template "faucet.name" . }}
    chart: {{ template "faucet.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
  name: faucet-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-provisioner
status: {}
