apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "condor-login.fullname" . }}
  labels:
    app: {{ template "condor-login.name" . }}
    chart: {{ template "condor-login.chart" . }}
    release: {{ .Release.Name }}
    instance:  {{ .Values.Instance }}
spec:
  selector:
    matchLabels:
      app: {{ template "condor-login.name" . }}
      instance: {{ .Values.Instance }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "condor-login.name" . }}
        chart: {{ template "condor-login.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: {{ include "condor-login.name" . }}-config
        configMap:
          name: {{ include "condor-login.fullname" . }}-config
          items:
           - key: tconfig-file.conf
             path: tconfig-file.conf
      - name: {{ include "condor-login.name" . }}-config-osg
        persistentVolumeClaim:
          claimName: {{ template "condor-login.name" . }}-config-osg
      - name: {{ include "condor-login.name" . }}-oasis
        persistentVolumeClaim:
          claimName: {{ template "condor-login.name" . }}-oasis
      - name: {{ include "condor-login.name" . }}-spt
        persistentVolumeClaim:
          claimName: {{ template "condor-login.name" . }}-spt
      - name: {{ include "condor-login.name" . }}-connect
        persistentVolumeClaim: 
          claimName: {{ template "condor-login.name" . }}-connect
      - name: {{ template "condor-login.name" . }}-hostcert
        secret:
          secretName: {{ .Values.HostCertSecret }}
          items:
          - key: hostcert.pem
            path: hostcert.pem
            mode: 420
      - name: {{ template "condor-login.name" . }}-hostkey
        secret:
          secretName: {{ .Values.HostKeySecret }}
          items:
          - key: hostkey.pem
            path: hostkey.pem
            mode: 384
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          env:
           - name: PASSWDFILE
             value: "root/tconfig-file.conf"
          image: "slateci/condor-login-node"
          imagePullPolicy: Always
          volumeMounts:
            - name: {{ include "condor-login.name" . }}-config
              mountPath:  /root/tconfig-file.conf
              subPath: tconfig-file.conf
            - name: {{ include "condor-login.name" . }}-config-osg
              mountPath: /cvmfs/config-osg.opensciencegrid.org
            - name: {{ include "condor-login.name" . }}-oasis
              mountPath: /cvmfs/oasis.opensciencegrid.org
            - name: {{ include "condor-login.name" . }}-spt
              mountPath: /cvmfs/spt.opensciencegrid.org
            - name: {{ include "condor-login.name" . }}-connect
              mountPath: /cvmfs/connect.opensciencegrid.org
            - name: {{ include "condor-login.name" . }}-hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: {{ include "condor-login.name" . }}-hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
