apiVersion: v1
kind: Service
metadata:
  name: {{ template "condor-ce.fullname" . }}
  labels:
    app: {{ template "condor-ce.fullname" . }}
    chart: {{ template "condor-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: ssh
    protocol: TCP
    name: ssh
  selector:
    app: {{ template "condor-ce.fullname" . }}
    instance: {{ .Values.Instance }}
release: {{ .Release.Name }}
