apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-configuration
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  99-local.ini: |
    [Site Information]
    group = {{ .Values.Site.Group }}
    host_name = localhost
    resource = {{ .Values.Site.Resource }}
    resource_group = {{ .Values.Site.ResourceGroup }}
    sponsor = {{ .Values.Site.Sponsor }}
    site_policy = UNAVAILABLE
    contact = {{ .Values.Site.Contact }}
    email = {{ .Values.Site.ContactEmail }}
    city = {{ .Values.Site.City }}
    country = {{ .Values.Site.Country }}
    latitude = {{ .Values.Site.Latitude }}
    longitude = {{ .Values.Site.Longitude }}

    [BOSCO]
    enabled = True
    users = {{ .Values.Cluster.Users }}
    endpoint =  {{ .Values.Cluster.Endpoint }}
    batch =  {{ .Values.Cluster.Batch }}
    ssh_key = /etc/osg/bosco.key
    max_jobs = {{ .Values.Cluster.MaxJobs }}

    [Misc Services]
    glexec_location = None
    edit_lcmaps_db = True
    authorization_method = vomsmap

    [Storage]
    se_available = False
    default_se = None
    grid_dir = {{ .Values.Storage.GridDir }}
    app_dir = UNSET
    data_dir = None
    worker_node_temp = {{ .Values.Storage.WorkerNodeTemp }}

    [Subcluster {{ .Values.Subcluster.Name }}]
    name = {{ .Values.Subcluster.Name }}
    node_count = {{ .Values.Subcluster.NodeCount }}
    ram_mb = {{ .Values.Subcluster.Memory }}
    cpu_model = Intel
    cpu_vendor = Intel
    cpu_speed_mhz =  2500
    cpus_per_node = {{ .Values.Subcluster.CpusPerNode }}
    cores_per_node = {{ .Values.Subcluster.CoresPerNode }}
    inbound_network = FALSE
    outbound_network = TRUE
    cpu_platform = x86_64
    max_wall_time = {{ .Values.Subcluster.MaxWallTime }}
    allowed_vos = {{ .Values.Subcluster.AllowedVOs }}


    [SE_dummy]
    enabled = False
    name = dummy
    srm_endpoint =  srm://srm.example.com:8443/srm/v2/server
    provider_implementation  = bestman
    implementation  = bestman


    [Squid]
    enabled = {{ .Values.Squid.Enabled }} 
    location =  {{ .Values.Squid.Location }}
    policy = DEFAULT
    cache_size = DEFAULT
    memory_size = DEFAULT
{{ if .Values.Cluster.GridmapOverride}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-grid-mapfile
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  grid-mapfile: |+
{{ .Values.GridmapOverride | indent 4 }}
{{ end }}
{{ if .Values.CustomizationScript}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  {{ .Values.Cluster.Batch }}-local-submit-attributes.sh: |+
{{ .Values.CustomizationScript | indent 4 }}
{{ end }}
---
