apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hostedce.fullname" . }}
  labels:
    app: {{ template "hostedce.fullname" . }}
    chart: {{ template "hostedce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "hostedce.fullname" . }}
      chart: {{ template "hostedce.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "hostedce.fullname" . }}
        chart: {{ template "hostedce.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: hostedce-{{ .Values.Instance }}-configuration
        configMap:
          name: hostedce-{{ .Values.Instance}}-configuration
      containers:
      - name: hostedce
        image: slateci/container-osg-hostedce:latest
        volumeMounts:
        - name: hostedce-{{ .Values.Instance}}-configuration
          mountPath: /etc/osg/config.d/99-local.ini
          subPath: 99-local.ini
        env:
        - name: _CONDOR_NETWORK_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
