apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    chart: {{ template "osg-hosted-ce.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
      chart: {{ template "osg-hosted-ce.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels: 
        app: {{ template "osg-hosted-ce.name" . }}
        chart: {{ template "osg-hosted-ce.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      volumes:
      - name: osg-hosted-ce-{{ .Values.Instance }}-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance}}-configuration
      {{ if .Values.Cluster.CustomizationScript }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
      {{ end }}
      - name: bosco-ssh-private-key-volume
        secret: 
          secretName: {{ .Values.Cluster.PrivateKeySecret }}
          items:
          - key: bosco.key
            path: bosco.key
            mode: 256
      hostNetwork: true
      containers:
      - name: osg-hosted-ce
        image: slateci/container-osg-hostedce:latest
        volumeMounts:
        - name: osg-hosted-ce-{{ .Values.Instance}}-configuration
          mountPath: /tmp/99-local.ini
          subPath: 99-local.ini
        - name: bosco-ssh-private-key-volume
          mountPath: /etc/osg/bosco.key
          subPath: bosco.key
        {{ if .Values.Cluster.CustomizationScript }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
          mountPath: /tmp/{{ .Values.Cluster.Batch }}_local_submit_attributes.sh
          subPath: {{ .Values.Cluster.Batch }}_local_submit_attributes.sh
        {{ end }}
        env:
        - name: _CONDOR_NETWORK_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENDPOINT
          value: {{ .Values.Cluster.Endpoint }}
        - name: CE_CONTACT
          value: {{ .Values.Site.ContactEmail }}
        - name: CE_USERS
          value: {{ .Values.Cluster.Users }}
        {{ if .Values.Cluster.CustomizationScript }}
        env:
        - name: LOCAL_ATTRIBUTES_FILE
          value: /tmp/{{ .Values.Cluster.Batch }}_local_submit_attributes.sh
        {{ end }}
