apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
  name: {{ template "gridftp.fullname" . }} 
  labels:
    app: {{ template "gridftp.fullname" . }}
    chart: {{ template "gridftp.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "gridftp.fullname" . }}
        chart: {{ template "gridftp.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      hostNetwork: true
      volumes:
        - name: gridftp-users
          secret:
            secretName: {{ .Values.GridFTPConfig.UserSecretName }} 
            defaultMode: 256
        - name: gridftp-host-pems
          secret:
            secretName: {{ .Values.GridFTPConfig.HostSecretName}} 
            defaultMode: 256
        {{ if .Values.GridFTPConfig.ExternalPath }}
        - name: dfs-volume
          hostPath:
          # directory location on host
            path: {{ .Values.GridFTPConfig.ExternalPath }}
        {{ end }}
      containers:
        - name: gridftp
          image: slateci/gridftp 
          volumeMounts:
            - name: gridftp-users
              mountPath: /opt/gridftp/users/
            - name: gridftp-host-pems
              mountPath: /tmp/gridftp-host-pems/
            {{ if .Values.GridFTPConfig.InternalPath }}
            - name: dfs-volume
              mountPath: {{ .Values.GridFTPConfig.InternalPath }}
            {{ end }}
      nodeSelector:
        gridftp: "true"
