apiVersion: v1
kind: ConfigMap
metadata:
  name: htcondor-{{ .Values.Instance }}-configuration
  labels:
    app: htcondor-submit-node
    instance: {{ .Values.Instance }}
data:
  condor_config.local: |-
{{ .Values.CondorConfigFile | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-publickey-{{ .Values.Instance }}
  labels:
    app: htcondor-submit-node
    instance: {{ .Values.Instance }}
data:
  authorized_keys: |-
{{ .Values.UserConfig.PublicKey | indent 4 }}
