apiVersion: v1
kind: Service
metadata:
  name: {{ template "htcondor-submit-node.fullname" . }}
  labels:
    app: {{ template "htcondor-submit-node.name" . }}
    chart: {{ template "htcondor-submit-node.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP 
  - port: 9618
    protocol: TCP
  selector:
    app: {{ template "htcondor-submit-node.name" . }}
    instance: {{ .Values.Instance }}
release: {{ .Release.Name }}
