# Label for this particular deployed instance
# Results in a name like "stashcache-[Instance]"
# Enables multiple instances of StashCache in one namespace
Instance: global

# Host Certificate and Key
# The following secrets are required
# The keys must be:
#    hostcert
#    hostkey
# run 'slate secret create --help' for usage
hostCertSecret: stashcache-cert-secret
hostKeySecret: stashcache-key-secret

Service:
  Port: 1094

Site:
  Name: "stashcache"

StashCache:
  # Local directory to be used as a cache
  CacheDirectory: /scratch
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.80
  # The amount of memory the cache is allowed to use (in GB)
  RamSize: 1g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 1M
  # to prefetch chunks that were not requested
  Prefetch: 0

authfileNoAuth: u * / rl

authfileAuth: u * / rl

stashcacheRobots: |-
  User-agent: *
  Disallow: /
