Instance: ''
replicaCount: 1
service:
  type: NodePort
  port: 29001
  annotations: login-service
HostKeySecret: hostkey
HostCertSecret: hostcert
LoginConfigFile: |+
   user_name:x:user_id:group_id::/home/user_name:/bin/bash:user_public_key

   user_name:x:user_id:group_id::/home/user_name:/bin/bash:user_public_key

   user_name:x:user_id:group_id::/home/user_name:/bin/bash:user_public_key
