Instance: ""

GlobusConfigFile: |-
  [Globus]
  User = %(GLOBUS_USER)s
  Password = %(GLOBUS_PASSWORD)s

  [Endpoint]
  Name = %(SHORT_HOSTNAME)s
  Public = True
  DefaultDirectory = /~/

  [Security]
  FetchCredentialFromRelay = True
  IdentityMethod = MyProxy

  [GridFTP]
  Server = %(HOSTNAME)s
  RestrictPaths = /etc

  [MyProxy]
  Server = %(HOSTNAME)s

  [OAuth]

