# Generates app name as "condor-[Instance]"
Instance: global

CondorConfig:
  # The address of your HTCondor Central Manager
  # If unspecified, then we will the central manager
  CollectorHost: localhost
  # If unspecified, defaults to 9618
  CollectorPort: 9618
  # The name of the secret that was created for your HTCondor password file
  # This must be created *BEFORE* you instantiate the chart.
  PasswordFileSecret: condor-password 

UserConfig:
  # Should not contain newlines
  PublicKey: |-
    ssh-rsa AAAA.... 

# The following is some extra configuration that we expose to users, but
# generally is not necessary to get an HTCondor head node running. You might
# want to change things here if, for example, your security policies or ports
# differ from our assumptions.
CondorConfigFile: |-
  CCB_ADDRESS                         = $(COLLECTOR_HOST)
  START                               = TRUE
  SUSPEND                             = FALSE
  PREEMPT                             = FALSE
  KILL                                = FALSE
  DAEMON_LIST                         = MASTER, SCHEDD, COLLECTOR, NEGOTIATOR
  ALLOW_WRITE                         = condor_pool@*, submit-side@matchsession
  SEC_DEFAULT_AUTHENTICATION          = PREFERRED
  SEC_DEFAULT_ENCRYPTION              = OPTIONAL
  SEC_DEFAULT_INTEGRITY               = REQUIRED
  SEC_DEFAULT_AUTHENTICATION_METHODS  = PASSWORD
  SEC_PASSWORD_FILE                   = /etc/condor/condor_password
  ALLOW_ADMINISTRATOR                 = condor_pool@*/*
  USE_SHARED_PORT                     = TRUE
  SHARED_PORT_PORT                    = 0
  RUNBENCHMARKS                       = FALSE
